plugins {
    alias(libs.plugins.android.library)
    id "realm-android"
}

android {
    namespace 'com.za.toptitup.loginlibrary'
    compileSdk 34
    buildFeatures {
        buildConfig true
    }
    defaultConfig {
        minSdk 23
        buildConfigField "long", "TIMESTAMP", System.currentTimeMillis() + "L"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
repositories {
    flatDir {
        dirs 'src/main/libs'
    }
}
dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.lifecycle.process
    implementation libs.lifecycle.common.jvm
    implementation libs.annotation.jvm
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation fileTree(include: ['*.jar', '*.aar'], dir: 'libs')

    implementation libs.rollingtext
    //The android-app-updater libary
    implementation libs.androidappupdatelibrary

    // implementation "org.json:json:20240303"

    implementation libs.retrofit
    implementation libs.retrofit2.converter.gson
    implementation libs.retrofit
    implementation libs.toasty.v125
    implementation libs.gson

    implementation libs.constraint.layout
    implementation libs.constraint.layout
    implementation libs.timber
    implementation libs.commons.lang3
    implementation libs.utilcode
    api libs.guava
    implementation libs.design
    implementation libs.support.v4
    implementation libs.material.ripple

    // implementation 'io.realm:android-adapters:2.3.0'
    implementation libs.glide
  //  implementation libs.lifecycle.extensions


    // implementation libs.extensions
    implementation libs.cardview.v7
    //  annotationProcessor "android.arch.lifecycle:compiler:1.1.1"// alternately-if using Java8, use following instead of compiler
    //  implementation "androidx. lifecycle:lifecycle-common-java8:*version*"
    implementation libs.lifecycle.common.java8 // Use the latest version
    implementation libs.android.common.java8
    implementation libs.glide.okhttp3.integration
    implementation libs.recyclerview
    implementation libs.firebase.crashlytics.v2003
    annotationProcessor libs.compiler
    implementation libs.glide.annotations
    implementation libs.logging.interceptor
    implementation libs.roundedimageview
    implementation files('src/main/libs/Android_Print_SDK_ESC_V1.11.jar')

    implementation files('src/main/libs/java-json.jar')
    implementation files('src/main/libs/SDK4BaseBinderV2.1.5.jar')
    implementation files('src/main/libs/SDK4EmvBinderV2.1.5.jar')
    implementation files('src/main/libs/SDK4KeyManagerBinderV2.1.5.jar')
    implementation files('src/main/libs/CashierInvoke_202002261912.jar')

    implementation files('src/main/libs/core-3.3.0.jar')
    implementation libs.android.gif.drawable
    implementation "io.realm:realm-android-library:10.19.0"

   // implementation libs.realm.android.library // Correct usage
    // kapt 'io.realm:realm-annotations:10.19.0' // Correct usage
    implementation libs.ccp // Check for the latest version
    implementation libs.libphonenumber
    implementation libs.google.firebase.crashlytics
    implementation libs.firebase.analytics // optional but recommended
    implementation libs.grenderg.toasty
    implementation(name: 'WiseSdk_D_1.09_00a_240325', ext: 'aar')
    implementation(name: 'WiseSdk_P_1.29_00a_24041501', ext: 'aar')


    api libs.grenderg.toasty
    // Check for the latest version
    //  implementation 'io.realm:android-adapters:3.1.0'

    //room db
    implementation libs.room.runtime
    //kapt "androidx.room:room-compiler:2.6.1"
    implementation (libs.zxing.android.embedded) {
        exclude group: 'com.google.zxing', module: 'core'
    }
    implementation "androidx.annotation:annotation:1.7.1"
    implementation "androidx.core:core-ktx:1.12.0"
    implementation "androidx.lifecycle:lifecycle-runtime:2.5.1"
    implementation "androidx.lifecycle:lifecycle-common-java8:2.5.1"



}