plugins {
    alias(libs.plugins.android.library)
}

android {
    namespace 'com.za.toptitup.loginlibrary'
    compileSdk 34

    defaultConfig {
        minSdk 23

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation fileTree(include: ['*.jar','*.aar'], dir: 'libs')

    implementation 'com.github.YvesCheung:RollingText:1.2.0'
    //The android-app-updater libary
    implementation 'com.github.Piashsarker:AndroidAppUpdateLibrary:1.0.3'


    implementation 'com.squareup.retrofit2:retrofit:2.11.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.11.0'
    implementation 'com.squareup.retrofit2:retrofit:2.11.0'
    implementation 'com.github.GrenderG:Toasty:1.2.5'
    implementation 'com.google.code.gson:gson:2.11.0'

    implementation 'com.android.support.constraint:constraint-layout:2.0.4'
    implementation 'com.android.support.constraint:constraint-layout:2.0.4'
    implementation 'com.jakewharton.timber:timber:5.0.1'
    implementation 'org.apache.commons:commons-lang3:3.17.0'
    implementation 'com.blankj:utilcode:1.30.7'
    api 'com.google.guava:guava:33.3.1-android'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.balysv:material-ripple:1.0.2'
    // implementation 'io.realm:android-adapters:2.3.0'
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    implementation "android.arch.lifecycle:extensions:1.1.1"
    implementation 'com.android.support:cardview-v7:28.0.0'
    //  annotationProcessor "android.arch.lifecycle:compiler:1.1.1"// alternately-if using Java8, use following instead of compiler
    //  implementation "androidx. lifecycle:lifecycle-common-java8:*version*"
    implementation 'androidx.lifecycle:lifecycle-common-java8:2.8.6' // Use the latest version
    implementation "android.arch.lifecycle:common-java8:1.1.1"
    implementation 'com.github.bumptech.glide:okhttp3-integration:4.16.0'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
    implementation 'com.google.firebase:firebase-crashlytics:20.0.3'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'
    implementation 'com.github.bumptech.glide:annotations:4.16.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.12.0'
    implementation 'com.makeramen:roundedimageview:2.3.0'
    implementation files('libs/Android_Print_SDK_ESC_V1.11.jar')

    implementation files('libs/java-json.jar')
    implementation files('libs/SDK4BaseBinderV2.1.5.jar')
    implementation files('libs/SDK4EmvBinderV2.1.5.jar')
    implementation files('libs/SDK4KeyManagerBinderV2.1.5.jar')
    implementation files('libs/CashierInvoke_202002261912.jar')

    implementation files('libs/core-3.3.0.jar')
    implementation 'pl.droidsonroids.gif:android-gif-drawable:1.2.29'
    implementation 'io.realm:realm-android-library:10.19.0' // Correct usage
   // kapt 'io.realm:realm-annotations:10.19.0' // Correct usage
    implementation libs.ccp // Check for the latest version
    implementation libs.libphonenumber
    implementation libs.google.firebase.crashlytics
    implementation libs.firebase.analytics // optional but recommended
    implementation libs.grenderg.toasty

    api 'com.github.GrenderG:Toasty:1.5.2'
    // Check for the latest version
    //  implementation 'io.realm:android-adapters:3.1.0'

    //room db
    implementation "androidx.room:room-runtime:2.6.1"
    //kapt "androidx.room:room-compiler:2.6.1"

}